package edu.carleton.dev.model;

import java.util.*;

public class Data {
    public static List<Lecture> lectures() {
        return new ArrayList<>(Arrays.asList(
                new Lecture("0", "Introduction to Javascript", new ArrayList<>(Collections.singletonList(new ListElement("Introduction to Javascript", "/slides/01-Introduction to Javascript.pdf"))), new ArrayList<>(Arrays.asList(new ListElement("Intro to Javascript Part 1 (Fall 2019)", "https://mediaspace.carleton.ca/media/2406b-sept6/1_tdi9wkpi"), new ListElement("Intro to Javascript Part 2 (Winter 2020)", "https://mediaspace.carleton.ca/media/2406-jan14/1_ic9zk1je"))), new ArrayList<>(Collections.singletonList(new ListElement("Intro to Javascript Code", "/code/Intro to Javascript Code.zip")))),
                new Lecture("0", "Javascript and the Document Object Model", new ArrayList<>(Collections.singletonList(new ListElement("Javascript and the Document Object Model", "/slides/02-Javascript and the Document Object Model.pdf"))), new ArrayList<>(Arrays.asList(new ListElement("Javascript and the DOM Part 1 (starts around 36:30) (Winter 2020)", "https://mediaspace.carleton.ca/media/2406-jan14/1_ic9zk1je"), new ListElement("Javascript and the DOM Part 2 + tutorial #2 discussion (Winter 2020)", "https://mediaspace.carleton.ca/media/2406-jan16/1_kndl42yy"))), new ArrayList<>(Collections.singletonList(new ListElement("Javascript and the DOM Code", "/code/Javascript and the DOM Code.zip")))),
                new Lecture("0", "Intro to Web Apps and HTTP", new ArrayList<>(Collections.singletonList(new ListElement("Intro to Web Apps and HTTP", "/slides/03-Intro to Web Apps and HTTP.pdf"))), new ArrayList<>(Arrays.asList(new ListElement("Intro to Web Apps and HTTP Part 1 (and Assignment #1 demo) (Winter 2020)", "https://mediaspace.carleton.ca/media/1_58d67hpu"), new ListElement("Intro to Web Apps and HTTP Part 2 (Winter 2020)", "https://mediaspace.carleton.ca/media/t/1_9jzumk00")))),
                new Lecture("0", "AJAX", new ArrayList<>(Collections.singletonList(new ListElement("AJAX", "/slides/04-AJAX.pdf"))), new ArrayList<>(Collections.singletonList(new ListElement("AJAX (starts around 19:30) (Winter 2020)", "https://mediaspace.carleton.ca/media/t/1_9jzumk00")))),
                new Lecture("0", "Client-Server Achitecture", new ArrayList<>(Collections.singletonList(new ListElement("Client-Server Achitecture", "/slides/05-Client-Server Architecture.pdf"))), new ArrayList<>(Arrays.asList(new ListElement("Client-Server Architecture Part 1 (starts at 1:06:00) (Winter 2020)", "https://mediaspace.carleton.ca/media/t/1_9jzumk00"), new ListElement("Client Server Architecture Part 2 (Winter 2020)", "https://mediaspace.carleton.ca/media/1_ogn5rof5")))),
                new Lecture("0", "Intro to Node.js", new ArrayList<>(Collections.singletonList(new ListElement("Intro to Node.js", "/slides/06-Intro to Node.pdf"))), new ArrayList<>(Arrays.asList(new ListElement("Intro to Node Part 1 (starts at 43:50) (Winter 2020)", "https://mediaspace.carleton.ca/media/1_ogn5rof5"), new ListElement("Intro to Node Part 2 (Winter 2020)", "https://mediaspace.carleton.ca/media/2406-jan30/1_1amuu28j"), new ListElement("Intro to Node Part 3 (Winter 2020)", "https://mediaspace.carleton.ca/media/2406-feb4/1_in4w4w16"))), new ArrayList<>(Arrays.asList(new ListElement("Intro to Node Code", "/code/Intro to Node Code.zip"), new ListElement("Iterating Object Keys and Retrieving Event Sources Code", "/code/Iterating Object Keys and Retrieving Event Sources Code-20200512.zip")))),
                new Lecture("0", "Node Package Manager (NPM)", new ArrayList<>(Collections.singletonList(new ListElement("07-Intro to NPM", "/slides/07-Intro to NPM.pdf"))), new ArrayList<>(Collections.singletonList(new ListElement("Intro to NPM (starts at 16:40) (Winter 2020)", "https://mediaspace.carleton.ca/media/2406-feb4/1_in4w4w16")))),
                new Lecture("0", "Template Engines", new ArrayList<>(Collections.singletonList(new ListElement("Template Engines", "/slides/08-Template Engines.pdf"))), new ArrayList<>(Arrays.asList(new ListElement("Template Engines Part 1 (starts at 40:00) (Winter 2020)", "https://mediaspace.carleton.ca/media/2406-feb4/1_in4w4w16"), new ListElement("Template Engines Part 2 (Winter 2020)", "https://mediaspace.carleton.ca/media/1_w2sshyc6"), new ListElement("Template Engines Part 3 (Winter 2020)", "https://mediaspace.carleton.ca/media/1_85to4kgx"))), new ArrayList<>(Collections.singletonList(new ListElement("Template Engine Code", "/code/Template-Engine-Code.zip")))),
                new Lecture("0", "RESTful Web Design", new ArrayList<>(Collections.singletonList(new ListElement("RESTful Web Design", "/slides/09-RESTful Web Design.pdf"))), new ArrayList<>(Arrays.asList(new ListElement("RESTful Web Design Part 1 (starts at 54:00) (Winter 2020)", "https://mediaspace.carleton.ca/media/1_85to4kgx"), new ListElement("RESTful Web Design Part 2 (Winter 2020)", "https://mediaspace.carleton.ca/media/2406-feb13/1_gckubhrr")))),
                new Lecture("0", "Middleware and Connect", new ArrayList<>(Collections.singletonList(new ListElement("Middleware and Connect", "/slides/10-Middleware and Connect.pdf"))), new ArrayList<>(Arrays.asList(new ListElement("Middleware and Connect Part 1 (starts at 47:00) (Winter 2020)", "https://mediaspace.carleton.ca/media/2406-feb13/1_gckubhrr"), new ListElement("Middleware and Connect Part 2 (Winter 2020)", "https://mediaspace.carleton.ca/media/2406-feb25/1_r4pin9f2"))), new ArrayList<>(Collections.singletonList(new ListElement("Middleware and Connect Code", "/code/Middleware-and-Connect-Code.zip")))),
                new Lecture("0", "Express", new ArrayList<>(Arrays.asList(new ListElement("Intro to Express", "/slides/11-Express.pdf"), new ListElement("More Express", "/slides/12-More Express.pdf"))), new ArrayList<>(Arrays.asList(new ListElement("Express Part 1 (starts at 35:15) (Winter 2020)", "https://mediaspace.carleton.ca/media/2406-feb25/1_r4pin9f2"), new ListElement("Express Part 2 (and A3 demonstration) (Winter 2020)", "https://mediaspace.carleton.ca/media/1_egqto831"), new ListElement("Express Part 3 (Winter 2020)", "https://mediaspace.carleton.ca/media/2406-mar5/1_v2zwb13t"), new ListElement("Express Part 4 (Winter 2020)", "https://mediaspace.carleton.ca/media/2406-mar10/1_enbl9gs4"))), new ArrayList<>(Arrays.asList(new ListElement("Intro to Express Code", "/code/Express-Code.zip"), new ListElement("More Express Base Code", "/code/More-Express-Base-Code.zip"), new ListElement("More Express Completed Code", "/code/More-Express-Completed-Code.zip")))),
                new Lecture("0", "MongoDB", new ArrayList<>(Arrays.asList(new ListElement("Intro to MongoDB", "/slides/13-Intro to MongoDB.pdf"), new ListElement("MongoDB and Node.js", "/slides/14-MongoDB and Node.pdf"), new ListElement("MongoDB and Node.js (Fall 2019)", "/slides/Mongo and Node-Fall2019.pdf"))), new ArrayList<>(Arrays.asList(new ListElement("MongoDB Part 1 (starts at 29:00) (Winter 2020)", "https://mediaspace.carleton.ca/media/2406-mar10/1_enbl9gs4"), new ListElement("MongoDB Part 2 (Winter 2020)", "https://mediaspace.carleton.ca/media/1_yuqceu1t"), new ListElement("MongoDB (Fall 2019)", "https://mediaspace.carleton.ca/media/1_wlnax17h"))), new ArrayList<>(Arrays.asList(new ListElement("MongoDB Code (Winter 2020)", "/code/MongoDB-Code.zip"), new ListElement("MongoDB Code (Fall 2019)", "/code/Mongo and Node Code.zip")))),
                new Lecture("0", "Mongoose", new ArrayList<>(Arrays.asList(new ListElement("Introduction to Mongoose", "/slides/Introduction to Mongoose.pdf"), new ListElement("More Mongoose", "/slides/More Mongoose.pdf"))), new ArrayList<>(Arrays.asList(new ListElement("Intro to Mongoose (Fall 2019)", "https://mediaspace.carleton.ca/media/2406-nov13/1_228yxe1o"), new ListElement("More Mongoose (Fall 2019)", "https://mediaspace.carleton.ca/media/1_uoqvgdh4"), new ListElement("Mongoose Wrap-up (Fall 2019)", "https://mediaspace.carleton.ca/media/2406-nov20/1_a6stgob0"))), new ArrayList<>(Arrays.asList(new ListElement("Intro to Mongoose Code", "/code/Intro-to-Mongoose-Code.zip"), new ListElement("More Mongoose Code", "/code/More-Mongoose-Code.zip")))),
                new Lecture("0", "Authentication, Authorization, and Sessions", new ArrayList<>(Arrays.asList(new ListElement("Authentication Authorization and Sessions", "/slides/Authentication Authorization and Sessions.pdf"), new ListElement("HTTPS", "/slides/HTTPS.pdf"))), new ArrayList<>(Arrays.asList(new ListElement("Authentication, Authorization, Sessions Part 1 (starts at 8:00) (Fall 2019)", "https://mediaspace.carleton.ca/media/2406-nov20/1_a6stgob0"), new ListElement("Authentication, Authorization, Sessions Part 2 (Fall 2019)", "https://mediaspace.carleton.ca/media/2406-nov22/1_4c8rnv58"))), new ArrayList<>(Arrays.asList(new ListElement("Authentication, Authorization, and Sessions Code", "/code/Authentication Authorization Sessions Code.zip"), new ListElement("HTTPS Server", "/code/HTTPS-Server.zip")))),
                new Lecture("0", "Web Sockets and Socket.io", new ArrayList<>(Collections.singletonList(new ListElement("Web Sockets and Socket.io", "/slides/07-Socket IO.pdf"))), new ArrayList<>(Collections.singletonList(new ListElement("Socket.io (Fall 2019)", "https://mediaspace.carleton.ca/media/2406-SEPT27/1_5jwqqfio"))), new ArrayList<>(Collections.singletonList(new ListElement("Socket.io Chat Code", "/code/SocketIO-ChatServerCode.zip")))),
                new Lecture("0", "Git and Heroku", new ArrayList<>(Collections.singletonList(new ListElement("Git and Heroku", "/slides/Heroku and Git.pdf"))), new ArrayList<>(Collections.singletonList(new ListElement("Git and Heroku (Fall 2019)", "https://mediaspace.carleton.ca/media/1_u3xnndw1")))

        )));
    }

    public static Lecture newLecture(String id, String unit) {
        return new Lecture(id, unit, new ArrayList<>(Collections.singletonList(new ListElement("Introduction to Javascript", "/slides/01-Introduction to Javascript.pdf"))), new ArrayList<>(Arrays.asList(new ListElement("Intro to Javascript Part 1 (Fall 2019)", "https://mediaspace.carleton.ca/media/2406b-sept6/1_tdi9wkpi"), new ListElement("Intro to Javascript Part 2 (Winter 2020)", "https://mediaspace.carleton.ca/media/2406-jan14/1_ic9zk1je"))), new ArrayList<>(Collections.singletonList(new ListElement("Intro to Javascript Code", "/code/Intro to Javascript Code.zip"))));
    }

    public static ArrayList<Tutorial> tutorials() {
        return new ArrayList<>(Arrays.asList(
                new Tutorial("0", "Tutorial 1", "Winter 2020", new ListElement("COMP2406-W20-T01", "/tutorials/winter2020/t1/COMP2406-W20-T01.pdf"), new ArrayList<>(Arrays.asList(new ListElement("stringproblems.js", "/tutorials/winter2020/t1/stringproblems.js"), new ListElement("students.js", "/tutorials/winter2020/t1/students.js")))),
                new Tutorial("0", "Tutorial 2", "Winter 2020", new ListElement("COMP2406-W20-T02.pdf", "/tutorials/winter2020/t2/COMP2406-W20-T02.pdf")),
                new Tutorial("0", "Tutorial 3", "Winter 2020", new ListElement("COMP2406-W20-T3.pdf", "/tutorials/winter2020/t3/COMP2406-W20-T3.pdf")),
                new Tutorial("0", "Tutorial 4", "Winter 2020", new ListElement("COMP2406-F19-T04", "/tutorials/winter2020/t4/COMP2406-F19-T04.pdf"), new ArrayList<>(Collections.singletonList(new ListElement("todo-server.zip", "/tutorials/winter2020/t4/todo-server.zip")))),
                new Tutorial("0", "Tutorial 5", "Winter 2020", new ListElement("COMP2406-F20-T05", "/tutorials/winter2020/t5/COMP2406-F20-T05.pdf"), new ArrayList<>(Arrays.asList(new ListElement("server.js", "/tutorials/winter2020/t5/server.js"), new ListElement("cards.json", "/tutorials/winter2020/t5/cards.json")))),
                new Tutorial("0", "Tutorials 6 and 7", "Winter 2020", new ListElement("COMP2406-W20-T0607", "/tutorials/winter2020/t6t7/COMP2406-W20-T0607.pdf"), new ArrayList<>(Collections.singletonList(new ListElement("T6-T7-BaseCode.zip", "/tutorials/winter2020/t6t7/T6-T7-BaseCode.zip")))),
                new Tutorial("0", "Tutorial 8", "Winter 2020", new ListElement("COMP2406-W20-T08", "/tutorials/winter2020/t8/COMP2406-W20-T08.pdf"), new ArrayList<>(Collections.singletonList(new ListElement("T08-BaseCode.zip", "/tutorials/winter2020/t8/T08-BaseCode.zip")))),
                new Tutorial("0", "Tutorial 9", "Winter 2020", new ListElement("COMP2406-W20-T09", "/tutorials/winter2020/t9/COMP2406-W20-T09.pdf"), new ArrayList<>(Collections.singletonList(new ListElement("T09-BaseCode.zip", "/tutorials/winter2020/t9/T09-BaseCode.zip")))),
                new Tutorial("0", "Tutorial 10", "Winter 2020", new ListElement("COMP2406-W20-T10", "/tutorials/winter2020/t10/COMP2406-W20-T10.pdf"), new ArrayList<>(Collections.singletonList(new ListElement("T10-Base-Code.zip", "/tutorials/winter2020/t10/T10-Base-Code.zip"))))
        ));
    }

    public static Tutorial newTutorial(String id, String name) {
        return new Tutorial(id, name, "Winter 2020", new ListElement("COMP2406-W20-T01", "/tutorials/winter2020/t1/COMP2406-W20-T01.pdf"), new ArrayList<>(Arrays.asList(new ListElement("stringproblems.js", "/tutorials/winter2020/t1/stringproblems.js"), new ListElement("students.js", "/tutorials/winter2020/t1/students.js"))));
    }

    public static ArrayList<Assignment> assignments() {
        return new ArrayList<>(Arrays.asList(
                new Assignment("0", "Assignment #1 - Client-side programming with Javascript", "Winter 2020", new ListElement("COMP2406-F20-A1 Specification", "/assignments/winter2020/a1/COMP2406-F20-A1 Specification.pdf"), new ArrayList<>(Arrays.asList(new ListElement("client.js", "/assignments/winter2020/a1/client.js"), new ListElement("add.jpg", "/assignments/winter2020/a1/add.jpg"), new ListElement("remove.jpg", "/assignments/winter2020/a1/remove.jpg"), new ListElement("example-menu-data.txt", "/assignments/winter2020/a1/example-menu-data.txt"), new ListElement("COMP2406-W20-A1 Marking Scheme", "/assignments/winter2020/a1/COMP2406-W20-A1 Marking Scheme.txt")))),
                new Assignment("0", "Assignment #2 - Server-side programming and AJAX", "Winter 2020", new ListElement("COMP2406-W20-A2 Specification", "/assignments/winter2020/a2/COMP2406-W20-A2 Specification.pdf"), new ArrayList<>(Arrays.asList(new ListElement("assignment2-basecode.zip", "/assignments/winter2020/a2/assignment2-basecode.zip"), new ListElement("COMP2406-W20-A2 Marking Scheme.txt", "/assignments/winter2020/a2/COMP2406-W20-A2 Marking Scheme.txt")))),
                new Assignment("0", "Assignment #3 - Express Restaurant Manager", "Winter 2020", new ListElement("COMP2406-W20-A3 Specification", "/assignments/winter2020/a3/COMP2406-W20-A3 Specification.pdf"), new ArrayList<>(Arrays.asList(new ListElement("A3-Data.zip", "/assignments/winter2020/a3/A3-Data.zip"), new ListElement("COMP2406-W20-A3 Marking Scheme.txt", "/assignments/winter2020/a3/COMP2406-W20-A3 Marking Scheme.txt")))),
                new Assignment("0", "Assignment #4 - MongoDB and Sessions", "Winter 2020", new ListElement("COMP2406-W20-A4 Specification", "/assignments/winter2020/a4/COMP2406-W20-A4 Specification.pdf"), new ArrayList<>(Arrays.asList(new ListElement("A4-Data.zip", "/assignments/winter2020/a4/A4-Data.zip"), new ListElement("A4 Demo Video", "https://mediaspace.carleton.ca/media/1_ym36jqpv"), new ListElement("COMP2406-W20-A4 Marking Scheme.txt", "/assignments/winter2020/a4/COMP2406-W20-A4 Marking Scheme.txt")))),
                new Assignment("0", "Final Assessment - Card Game Trading", "Winter 2020", new ListElement("COMP2406-W20-A5 Specification", "/assignments/winter2020/a5/COMP2406-W20-A5 Specification.pdf"), new ArrayList<>(Arrays.asList(new ListElement("database-initializer.js", "/assignments/winter2020/a5/database-initializer.js"), new ListElement("A5 Demo Video", "https://mediaspace.carleton.ca/media/1_a68wh0k1"), new ListElement("COMP2406-W20-A5 Marking Scheme.txt", "/assignments/winter2020/a5/COMP2406-W20-A5 Marking Scheme.txt")))),
                new Assignment("0", "Assignment #1 - Client-side programming with Javascript", "Fall 2019", new ListElement("COMP2406-F19-A1 Specification", "/assignments/fall2019/a1/COMP2406-F19-A1 Specification.pdf"), new ArrayList<>(Arrays.asList(new ListElement("trivia.js", "/assignments/fall2019/a1/trivia.js"), new ListElement("check.png", "/assignments/fall2019/a1/check.png"), new ListElement("x.png", "/assignments/fall2019/a1/x.png"), new ListElement("COMP2406-F19-A1 Marking Scheme.txt", "/assignments/fall2019/a1/COMP2406-F19-A1 Marking Scheme.txt")))),
                new Assignment("0", "Assignment #2 - Real-time communication using Socket.io", "Fall 2019", new ListElement("COMP2406-F19-A2 Specification.pdf", "/assignments/fall2019/a2/COMP2406-F19-A2 Specification.pdf"), new ArrayList<>(Arrays.asList(new ListElement("COMP2406-F19-A2 Marking Scheme.pdf", "/assignments/fall2019/a2/COMP2406-F19-A2 Marking Scheme.pdf")))),
                new Assignment("0", "Assignment #3 - Trivia Question Web Service", "Fall 2019", new ListElement("COMP2406-F19-A3 Specification", "/assignments/fall2019/a3/COMP2406-F19-A3 Specification.pdf"), new ArrayList<>(Arrays.asList(new ListElement("A3-Resources.zip", "/assignments/fall2019/a3/A3-Resources.zip"), new ListElement("marking scheme.txt", "/assignments/fall2019/a3/marking scheme.txt")))),
                new Assignment("0", "Assignment #4 - Trivia Quiz Builder Using MongoDB", "Fall 2019", new ListElement("COMP2406-F19-A4 Specification", "/assignments/fall2019/a4/COMP2406-F19-A4 Specification.pdf"), new ArrayList<>(Arrays.asList(new ListElement("database-initializer.js", "/assignments/fall2019/a4/database-initializer.js"), new ListElement("COMP2406-F19-A4 Marking Scheme.txt", "/assignments/fall2019/a4/COMP2406-F19-A4 Marking Scheme.txt")))),
                new Assignment("0", "Assignment #5 - Sessions and User Profiles", "Fall 2019", new ListElement("COMP2406-F19-A5-Specification", "/assignments/fall2019/a5/COMP2406-F19-A5-Specification.pdf"), new ArrayList<>(Arrays.asList(new ListElement("A5-BaseCode.zip", "/assignments/fall2019/a5/A5-BaseCode.zip"), new ListElement("COMP2406-F19-A5 Marking Scheme.txt", "/assignments/fall2019/a5/COMP2406-F19-A5 Marking Scheme.txt"))))
        ));
    }

    public static Assignment newAssignment(String id, String name) {
        return new Assignment(id, name, "Winter 2020", new ListElement("COMP2406-F20-A1 Specification", "/assignments/winter2020/a1/COMP2406-F20-A1 Specification.pdf"), new ArrayList<>(Arrays.asList(new ListElement("client.js", "/assignments/winter2020/a1/client.js"), new ListElement("add.jpg", "/assignments/winter2020/a1/add.jpg"), new ListElement("remove.jpg", "/assignments/winter2020/a1/remove.jpg"), new ListElement("example-menu-data.txt", "/assignments/winter2020/a1/example-menu-data.txt"), new ListElement("COMP2406-W20-A1 Marking Scheme", "/assignments/winter2020/a1/COMP2406-W20-A1 Marking Scheme.txt"))));
    }

    public static List<User> users() {
        return new ArrayList<>(
                Arrays.asList(
                        new User("admin", "admin", "admin@carleton.ca", "\\\\www.gravatar.com/avatar/a59bead6ed0ffa1b4917370df569b8fb?s=200&r=pg&d=identicon"),
                        new User("student", "student", "student@carleton.ca", "\\\\www.gravatar.com/avatar/e95b53a5008163da29f10fb33185fccf?s=200&r=pg&d=identicon")
                )
        );
    }

    public static User getUser(String username) {
        Optional<User> found = users().stream().filter(user -> user.getEmail().equals(username)).limit(1).findAny();
        return found.orElse(null);
    }
}
