name: release

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install dependencies
        run: npm install
      - name: Build application for deployment
        run: npm run build:gh-pages
      - name: Build react storybook
        run: npm run build:storybook:react
      - name: Build web components storybook
        run: npm run build:storybook:wc
      - name: Build Java TODO example app
        run: |
          mvn -B package --file src/java-todo/pom.xml
          mkdir dist/java-todo && cp src/java-todo/target/java-todo-example-1.0.war dist/java-todo/app.war
          unzip dist/java-todo/app.war -d dist/java-todo
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
